package interfaces;

public interface Allowance {
    double JUNIOR_PROGRAMMER_ALLOWANCE_PERCENT = 0.1, SENIOR_PROGRAMMER_ALLOWANCE_PERCENT = 0.2,
    JUNIOR_PROJECTLEAD_ALLOWANCE_PERCENT = 0.05, SENIOR_PROJECTLEAD_ALLOWANCE_PERCENT = 0.15, ANALYST_ALLOWANCE_PERCENT = 0.05;
  
    void calculateAllowance();  
}
